application:
  version: '@project.version@'

logging:
  pattern:
    level: '%5p [%X{traceId:-}:%X{spanId:-}]'

spring:
  profiles:
    active: @spring.profiles.active@
  output:
    ansi:
      enabled: always