application:
  version: '@project.version@'
  asset-service:
    url: http://localhost:8080

logging:
  pattern:
    level: '%5p [%X{traceId:-}:%X{spanId:-}]'

spring:
  profiles:
    active: @spring.profiles.active@
  application:
    name: '@project.name@'
  output:
    ansi:
      enabled: always
  data:
    mongodb:
      host: localhost
      database: test-data