application:
  version: '@project.version@'

logging:
  pattern:
    level: '%5p [%X{traceId:-}:%X{spanId:-}]'

spring:
  profiles:
    active: local
  application:
    name: '@project.name@'
  output:
      ansi:
        enabled: always
  data:
    mongodb:
      database: app-data

springdoc:
  default-produces-media-type: application/json
  show-actuator: 'true'

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  metrics:
    mongo:
      command:
        enabled: false     
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  endpoint:
    configprops:
      show-values: always
    env:
      show-values: always
    health:
      show-details: always
      show-components: always    
  info:
    os:
      enabled: 'true'
    java:
      enabled: 'true'