application:
  version: '@project.version@'

logging:
  pattern:
    level: '%5p [%X{traceId:-}:%X{spanId:-}]'

spring:
  application:
    name: '@project.name@'
  output:
      ansi:
        enabled: always
  data:
    mongodb:
      host: localhost
      database: app-data

springdoc:
  default-produces-media-type: application/json
  show-actuator: 'true'

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  metrics:
    mongo:
      command:
        enabled: false     
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      show-components: always
  info:
    os:
      enabled: 'true'
    java:
      enabled: 'true'
    build:
      enabled: 'true'