version: "3.9"

services:
  mongo:
    image: @docker-image-mongodb@
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge
