services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-tier
  springboot3andjava17:
    image: spring-boot-3-and-java-17:0.0.1-SNAPSHOT
    container_name: springboot3andjava17
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    networks:
      - app-tier

volumes:
  mongodb_data:

networks:
  app-tier:
    driver: bridge