application:
  version: '@project.version@'

mqtt:
  host: homeassistant
  port: 1883
  clientId: ${spring.application.name}
  username: @mqtt.username@
  password: @mqtt.password@

logging:
  pattern:
    level: '%5p [%X{traceId:-}:%X{spanId:-}]'

spring:
  profiles:
    active: @spring.profiles.active@
  application:
    name: '@project.name@'
  output:
    ansi:
      enabled: always