application:
  asset-service:
    url: http://localhost:8080

mqtt:
  host: homeassistant
  port: 1883
  clientId: ${spring.application.name}
  username: @mqtt.username@
  password: @mqtt.password@

spring:
  kafka:
    bootstrap-servers: localhost:9094