spring:
  config:
    import: application-core.yml
  application:
    name: '@project.name@'
  docker:
    compose:
      file: @docker-compose-path@
  kafka:
    client-id: '@project.name@'
    listener:
      log-container-config: true
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

