logging:
  pattern:
    level: '%5p [%X{traceId:-}:%X{spanId:-}]'

spring:
  application:
    name: @project.name@
  profiles:
    active: @spring.profiles.active@
  output:
    ansi:
      enabled: always
  kafka:
    client-id: @project.name@