spring:
  config:
    import: application-core.yml
  application:
    name: @project.name@
  data:
    mongodb:
      database: app-data

springdoc:
  default-produces-media-type: application/json
  show-actuator: true
  writer-with-default-pretty-printer: true

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  metrics:
    mongo:
      command:
        enabled: false     
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: *
  endpoint:
    configprops:
      show-values: always
    env:
      show-values: always
    health:
      show-details: always
      show-components: always    
  info:
    os:
      enabled: true
    java:
      enabled: true