application:
  version: @project.version@

server:
  port: 8081

logging:
  pattern:
    level: '%5p [%X{traceId:-}:%X{spanId:-}]'

spring:
  application:
    name: @project.name@
  profiles:
    active: @spring.profiles.active@
  output:
    ansi:
      enabled: always
  data:
    mongodb:
      database: app-data

springdoc:
  default-produces-media-type: application/json
  show-actuator: true
  writer-with-default-pretty-printer: true

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  endpoint:
    configprops:
      show-values: always
    env:
      show-values: always
    health:
      show-details: always
      show-components: always    
  info:
    os:
      enabled: true
    java:
      enabled: true